# Site settings
title: Ley de Probidad
email: info@ciudadanointeligente.org
phone: +56224192770
address: "Holanda 895, Providencia, Santiago"
developedby: "Ciudadano Inteligente"
description: Chile necesita una Ley de Probidad ahora.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leydeprobidad.cl" # the base hostname & protocol for your site
twitter_username: ciudadanoi

# Build settings
markdown: kramdown

collections:
  persons:
    output: true